import numpy as np
from pathlib import Path
from ultralytics import YOLO
from src.utils import ml_stratifiers
from collections import Counter
import matplotlib.pyplot as plt
from src.config import (MAX_RETRIES)

import os
import shutil
import yaml
import torch
import sys
import time

class Trainer:

    """Base Class containing YOLO methods for optimized training & tuning of models

    @author: Sami Ibrahim
    @version: 8/19/2026

    Methods:
        __init__: Initiates an instance of the class with no attributes
        train: base method for training the model
        tune: base method for model hyperparameter tuning

        validate_cuda(): Helper for checking if the client is running the model on their cpu or gpu

        _run : internal run method used by train and tune
    """

    def __init__(self) -> None:
        """
        Initializes the Trainer class

        Args:
            model (YOLO) : YOLO object generated with chosen model
            latest_results (Results) : The most recent Results object generated post training by the model
            run_name (str) : name of the current or latest run e.g. train_yolo26s-seg_imgsz_640_epochs_100
        
        Returns:
            None
        """

        self.model = None
        self.latest_results = None
        self.run_name = None


    @staticmethod
    def validate_cuda() -> None:
        """
        Helper for checking if the client is running the model on their cpu or gpu and prompting
        whether they would like to continue if cpu

        Args: 
            None

        Returns:
            None
        """

        if torch.cuda.is_available():
            print(f"GPU detected: {torch.cuda.get_device_name(0)}")
            print(f"CUDA version: {torch.version.cuda}")
            return

        print("WARNING: CUDA is not available.")
        print("Training will run on the CPU and may be significantly slower.")

        response = input("Continue anyway? (y/n): ").strip().lower()

        if response not in {"y", "yes"}:
            print("Training cancelled.")
            sys.exit(0)


    def train(self, cfg : Path | str="args.yaml", current_proj_dir : Path | str | None=None, resume : str | Path | None=None):
        """
        Base method for training a model using the provided parameters from a yaml file

        Args:
            cfg (Path | str) : configuration file with arguments/parameters to train model with (default is args.yaml)
            current_proj_dir (Path | str | None): path to current working project (will save in current working dir if None)
            resume (Path | str | None): path to .pt model file to resume from 

        Returns:
            Results object generated by model
        """

        return self._run(cfg=cfg, current_proj_dir=current_proj_dir, tune=False, resume=resume)


    def tune(self, cfg : Path | str="args.yaml", current_proj_dir : Path | str | None=None):
        """
        Tunes the model hyperparameters using the provided data and saves the best hyperparameters to a file
        
        Args:
            cfg (Path | str) : path to configuration file
            current_proj_dir (Path | str | None): path to current working project (will save in current working dir if None)

        Returns:
            Results object generated by the model
        """

        return self._run(cfg=cfg, current_proj_dir=current_proj_dir, tune=True)


    def _run(self, 
             cfg : Path | str="args.yaml", 
             current_proj_dir : Path | str | None=None, 
             tune : bool=False, 
             resume : str | Path | None=None):
        """
        Internal Method for running either the YOLO tune or train calls
        Will retry a total of maximum of MAX_RETRIES times upon training or tuning failure

        Args:
            cfg (Path | str): yaml configuration file path (default is args.yaml)
            current_proj_dir (Path | str | None): current working project's path (will save in current working dir if None)
            tune (bool) : if true will begin or resume hyperparameter tuning
            resume (str | Path | None) : path to .pt model file to resume from

        Raises:
            ValueError if a model name isn't found in the yaml config

        Returns :
            Results obj generated by the model 
        """
        Trainer.validate_cuda()
        project_dir = Path(current_proj_dir or Path.cwd())

        with open(cfg, "r") as f:
            data = yaml.safe_load(f)

        model_name = data.get("model")
        imgsz = data.get("imgsz")
        epochs = data.get("epochs")

        if model_name is None:
            raise ValueError("No 'model' entry found in yaml config")
        
        self.model = YOLO(model_name)

        name = "tune" if tune else "train"

        # proper naming convention e.g. train_yolo26s_imgsz_640_epochs_100; feel free to change this
        self.run_name = f"{name}_{Path(model_name).stem}_imgsz_{imgsz}_epochs_{epochs}"
        run_dir = project_dir / "runs" / self.run_name

        for attempt in range(MAX_RETRIES):
            try:
                print(f"{'Resuming' if resume is not None else 'Starting'} {name} run")

                if tune:
                    exists = run_dir.exists()

                    self.latest_results = self.model.tune(
                        iterations=data.get("iterations"),
                        data=data.get("data"),
                        epochs= epochs,
                        imgsz=imgsz,
                        project=project_dir / "runs" / self.run_name,
                        resume = exists
                    )
                else:
                    if resume is not None:
                        self.model = YOLO(str(resume))
                        self.latest_results = self.model.train(resume=True)
                    else:
                        self.latest_results = self.model.train(
                            cfg=cfg,
                            project = project_dir / "runs",
                            name = self.run_name
                        )
                break

            except KeyboardInterrupt:
                raise

            except PermissionError:
                print("Permission issue detected, retrying...")
                time.sleep(20)
                continue

            except Exception as e:
                print(f"{name.capitalize()} failed: {e}")

                # Resume from latest checkpoint here
                checkpoints = list((project_dir / "runs").glob(f"{self.run_name}*/weights/last.pt"))
                latest_checkpoint = max(checkpoints, key=lambda p : p.stat().st_mtime, default=None)

                if latest_checkpoint:
                    print(f"Found checkpoint: {latest_checkpoint}")
                    resume = latest_checkpoint

                if attempt == MAX_RETRIES - 1:
                    raise

                print("Retrying in 20 seconds...")
                time.sleep(20)

        return self.latest_results


    @staticmethod
    def stratified_split(self, 
                         data_dir : str | Path, 
                         data_yaml : str | Path="data.yaml", 
                         train_pct : float=0.8, 
                         current_proj_dir : str | Path | None=None):
        """
        Performs a stratified split of the dataset into training and validation sets based on the provided percentage
        Uses MultilabelStratifiedShuffleSplit instead of the scikit-learn standard stratified splits to preserve the
        distribution of labels across both validation and training sets. It is useful for an imbalanced dataset.
        Scikitlearn standard stratified split only uses one array to represent the class count

        Note: This is better for a smaller more constrained data set. Completely random splits are better for larger,
              more balanced datasets.

        Args:
            data_dir (str | Path): Path to the directory containing the dataset
            yaml (str | Path): Path to the YOLO data.yaml file (default is "data.yaml")
            train_pct (float): Percentage of data to be used for training (default is 0.8)
            current_proj_dir (str | Path | None) : path to current project directory (will save in current working dir if None)
        
        Raises:
            ValueError: If the dataset folder is not found or if train_pct is not between 0.01 and 0.99 or 
                if the class names cannot be loaded from the YAML file

        Returns:
            None
        """

        if not os.path.isdir(data_dir):
            raise ValueError("Dataset folder not found.")
        if train_pct <= 0.01 or train_pct >= 0.99:
            raise ValueError("train_pct must be between 0.01 and 0.99")

        # Loading the class names from the YAML file
        with open(data_yaml, "r") as f:
            data_yaml = yaml.safe_load(f)

        class_names = data_yaml.get("names", [])   
        if not class_names:
            raise ValueError("No class names found in data.yaml")
        
        num_classes = len(class_names)
        print(f"\nFound {num_classes} classes: {class_names}")
        for i, name in enumerate(class_names):
            print(f"{i}: {name}")

        # Initializing paths for images and labels
        input_image_path = Path(data_dir) / "images"
        input_label_path = Path(data_dir) / "labels"

        if current_proj_dir is None:
            cwd = Path.cwd()
        else:
            cwd = current_proj_dir

        train_img_path = cwd / "data" / "train" / "images"
        train_lbl_path = cwd / "data" / "train" / "labels"
        val_img_path = cwd / "data" / "val" / "images"
        val_lbl_path = cwd / "data" / "val" / "labels"

        for folder in [train_img_path, train_lbl_path, val_img_path, val_lbl_path]:
            folder.mkdir(parents=True, exist_ok=True)  # Create the folders if they don't exist

        # Building Mutilabel Indicator Matrix e.g. shown below
        image_ids = []
        label_vectors = []

        label_files = list(input_label_path.glob("*.txt"))
        print(f"\nFound {len(label_files)} label files")

        for txt_file in label_files:
            # using a set so duplicates are stored uniquely
            classes_present = set()

            # Class example stored like for line 1 e.g.
            # 2 0.604 0.54 0.592 0.54 0.588 0.544 0.584 where 2 is the id
            with open(txt_file, "r") as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) == 0:
                        continue
                    try:
                        class_id = int(parts[0])
                        if 0 <= class_id < num_classes:
                            classes_present.add(class_id)
                    except ValueError:
                        continue

            # creates a empty list
            multi_hot = [0] * num_classes
            for cls in classes_present:
                multi_hot[cls] = 1

            # image_ids = ["img1", "img2", "img3"]
            # multi_hot = [0, 1, 0, 1]  4 classes, class 1 and 3 are present
            # label_vectors = [ [0,1,0,1] for img1, [blah, blah, blah, blah] for img2, etc...]
            image_ids.append(txt_file.stem)
            label_vectors.append(multi_hot)

        # Splitting the dataset using the ml_stratifiers lib
        label_vectors = np.array(label_vectors)
        # For k fold cross validation recommend looking into n_splits > 1 (but for a larger dataset)
        # random state=43 (could be any number) such that each run is identically split for debugging
        msss = ml_stratifiers.MultilabelStratifiedShuffleSplit(n_splits=1, test_size=(1 - train_pct), random_state=42) 
        (train_idx, val_idx) = next(msss.split(image_ids, label_vectors))

        train_images = [image_ids[i] for i in train_idx]
        val_images = [image_ids[i] for i in val_idx]
        print(f"\nTrain Images: {len(train_images)}")
        print(f"Validation Images: {len(val_images)}")

        def find_image(image_id):
            IMAGE_EXTENSIONS = [
                ".jpg",
                ".jpeg",
                ".png",
                ".bmp",
                ".tif",
                ".tiff",
                ".webp"
            ]
            for ext in IMAGE_EXTENSIONS:
                candidate = input_image_path / f"{image_id}{ext}"
                if candidate.exists():
                    return candidate
            return None

        # Copy Train Files
        print("\nCopying training files...")
        for image_id in train_images:
            image_file = find_image(image_id)
            label_file = input_label_path / f"{image_id}.txt"

            shutil.copy2(image_file, train_img_path / image_file.name)
            shutil.copy2(label_file,train_lbl_path / label_file.name)

        # Copy Validation Files
        print("Copying validation files...")
        for image_id in val_images:

            image_file = find_image(image_id)
            if image_file is None:
                continue

            label_file = input_label_path / f"{image_id}.txt"
            shutil.copy2(image_file, val_img_path / image_file.name)
            shutil.copy2(label_file, val_lbl_path / label_file.name)
        print("\nDataset split complete.")
        
        # Generate Statistics
        train_counter = Trainer.count_yolo_labels(train_lbl_path)
        val_counter = Trainer.count_yolo_labels(val_lbl_path)

        Trainer.print_distribution(train_counter, class_names, "TRAIN")
        Trainer.print_distribution(val_counter, class_names, "VALIDATION")

        # Generate Graphs
        Trainer.plot_distribution(train_counter, class_names, "Train Label Distribution", cwd / "train_distribution.png")
        Trainer.plot_distribution(val_counter, class_names, "Validation Label Distribution", cwd / "val_distribution.png")
        print("\nDone!")
        print("Generated:")
        print("  train_distribution.png")
        print("  val_distribution.png")


    @staticmethod
    def count_yolo_labels(labels_dir : str | Path) -> Counter:
        """
        Count object instances from YOLO label files. 
        Intended to be used with stratified_split as it counts class image presence via a set e.g. class 0 or 1 it appears in image50, 
        but not the raw count of classes e.g. class 0 appears 20 times in image50

        Note: raw count balances can be messy, class image presence distribution is cleaner

        Args:
            labels_dir (str | Path): path to labels directory

        Returns:
            counter  
        """
        counter = Counter()
        txt_files = list(Path(labels_dir).rglob("*.txt"))

        for txt_file in txt_files:
            with open(txt_file, "r") as f:
                for line in f:
                    parts = line.strip().split()
                    if not parts:
                        continue
                    try:
                        class_id = int(parts[0])
                        counter[class_id] += 1
                    except ValueError:
                        continue
        return counter


    @staticmethod
    def print_distribution(counter : Counter, class_names : list[str], split_name : str) -> None:
        """
        Helper method of stratified_split used to print the raw class distribution
        
        Args:
            counter (Counter) : count distribution of class/labels
            class_names (list[str]) : list of str class names
            split_name (str) : name of the corresponding split; usually "TEST" or "VAL"
        
        Returns:
            None
        """
        total = sum(counter.values())

        print(f"\n{'=' * 50}")
        print(f"{split_name} DISTRIBUTION")
        print(f"{'=' * 50}")

        for class_id, count in sorted(counter.items()):

            class_name = (
                class_names[class_id]
                if class_id < len(class_names)
                else f"Class {class_id}"
            )

            percentage = (count / total * 100) if total else 0

            print(
                f"{class_name:<15}"
                f"{count:>8} labels"
                f" ({percentage:.2f}%)"
            )


    @staticmethod
    def plot_distribution(counter : Counter, class_names : list[str], title : str, output_file : str | Path) -> None:
        """
        Generates a bar graph distribution of classes/labels. Helper Method used for stratified split

        Args:
            counter (Counter) : count distribution of class/labels
            class_names (list[str]) : list of str class names
            title (str) : graph title
            output_file (str | Path) : output directory + file name
        
        Returns:
            None
        """
        class_ids = sorted(counter.keys())
        counts = [counter[cid] for cid in class_ids]
        labels = [class_names[cid] if cid < len(class_names) else f"Class {cid}" for cid in class_ids]

        plt.figure(figsize=(12, 6))
        bars = plt.bar(labels, counts)

        plt.title(title)
        plt.xlabel("Class")
        plt.ylabel("Number of Labels")

        plt.xticks(rotation=45)

        for bar, count in zip(bars, counts):
            plt.text(
                bar.get_x() + bar.get_width() / 2,
                count,
                str(count),
                ha="center",
                va="bottom"
            )

        plt.tight_layout()
        plt.savefig(output_file, dpi=300)

        print(f"\nSaved graph: {output_file}")

        plt.close()