from ultralytics import YOLO

class Trainer:
    """ Class for training model

    @author: Sami Ibrahim
    @version: 8/19/2026

    # should read from an args list generated by evaluator or manually and train the model using that
    # begin training in parallel (for a more powerful computer I guess)
    # continue loop on failure (sometimes stuff breaks)
    # 

    Methods:
        __init__:
    """

    def __init__(self, model):
        """
        Initializes blah

        Args:
            model: pre-trained model to load
        """
        self.model = YOLO(model)

    def train(self):
        return self.model.train(import from args.yaml)

    